- { name: vm,                        images: ["ubuntu-noble", "ubuntu-jammy", "debian-12", "almalinux-9"] }
- { name: github_runner_ubuntu_2404, images: ["github-ubuntu-2404"], details: {repo_name: ubicloud/github-e2e-test-workflows, workflow_name: test_2404.yml, branch_name: main} }
- { name: github_runner_ubuntu_2204, images: ["github-ubuntu-2204"], details: {repo_name: ubicloud/github-e2e-test-workflows, workflow_name: test_2204.yml, branch_name: main} }
- { name: postgres_standard,         images: ["postgres-ubuntu-2204"] }
- { name: postgres_ha,               images: ["postgres-ubuntu-2204", "ubuntu-jammy"] }
- { name: kubernetes,                images: ["kubernetes-v1_34"]}
